void imprime_apellidos(char desde, char hasta);
int imprime_lista(struct cliente* lista);
int imprime_lista_detalle(struct cliente* it, int cantidad_clientes);
void imprime_transacciones(struct transaccion* it);
void imprime_cliente(struct cliente* cliente, int indice);
void imprime_cliente_detalle(struct cliente* cliente);
void pausa_enter();
void limpia_buffer();
void mensaje_feedback(char mensaje[200]);
int pide_opcion(int rango);
void Formato_Titulos(char titlulo[100]);
